name: Environment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
      - test

jobs:
  environment-pipeline:
    runs-on: ubuntu-latest

    env:
      ENV_SECRET: ${{ secrets.ENV_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "Setting up environment"

      - name: Consume secret
        run: |
          echo "Consuming secret: $ENV_SECRET"

      - name: Output environment
        run: |
          echo "## Chosen Environment: ${{ github.event.inputs.environment }}" > output.md

      - name: Echo environment variable
        run: | 
          echo "Environment variable: $ENV_SECRET"
